version: 1.9.0
compose-app: docker-compose
env-file: .env

service-groups:
  - name: airflow
    project-name: egh-airflow
    compose-path:
      - containers/compose-airflow.yaml
    env-file: containers/airflow/.env
    services:
      default: startup
      available:
        - name: postgres
        - name: redis
        - name: webserver
        - name: scheduler
        - name: worker
        - name: triggerer
        - name: airflow-cli
