version: '3.4'
services:

  superset:
    depends_on:
      - postgres
      - redis
      - flower

  airflow:
    depends_on:
      - postgres
      - redis
      - flower

  postgres:
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
      - ./postgresql/sql/dev/01-database.sql:/docker-entrypoint-initdb.d/11-database.sql
      - ./postgresql/sql/dev/02-epigraphhub.sql:/docker-entrypoint-initdb.d/12-epigraphhub.sql

volumes:
  pgdata:
