version: '3.4'
services:

  epigraphhub:
    depends_on:
      - epigraphhub-db

  epigraphhub-db:
    environment:
      # overwrite .env default variables
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 25432:25432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 25432 -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    command: -p 25432
