version: '3.4'
services:

  superset:
    depends_on:
      - postgres
      - redis
      - flower

  postgres:
    environment:
      # overwrite .env default variables
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - ${POSTGRES_PORT}:25432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${POSTGRES_PORT} -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    command: -p 25432
