version: '3.4'
services:

  epigraphhub:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SUPERSET_PORT}/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 40s  # requires docker-compose 3.4
    volumes:
      - ..:/opt/EpiGraphHub
    network_mode: host
