version: '3.4'
services:

  epigraphhub-superset:
    depends_on:
      - epigraphhub-db
      - epigraphhub-celery
    volumes:
      - ..:/opt/EpiGraphHub
      - ${SUPERSET_DB_PATH_HOST}:/opt/data/superset/superset.db
