version: '3.4'
services:

  superset:
    depends_on:
      - postgres
      - redis
      - flower

  postgres:
    env_file:
      - ../.env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      # overwrite .env default variables
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgresql/sql/dev/:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data
    command: -p ${POSTGRES_PORT}



volumes:
  pgdata:
