FROM postgis/postgis:13-3.2

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y \
    && apt-get install -y \
      postgresql-13-plr \
      postgresql-13-postgis-3-scripts \
      postgresql-plpython3-13 \
      postgresql-contrib \
    && rm -rf /var/lib/apt/lists/*
