version: '3.4'
services:

  epigraphhub:
    image: epigraphhub
    env_file:
      - ../.env
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        # note: if you want to use a specific UID and GID, ensure to add it to
        #       the .env file
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        
  dev-epigraphhub:
    image: epigraphhub
    env_file:
      - ../.env
    depends_on:
      - dev-epigraphhub-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 40s  # requires docker-compose 3.4
    volumes:
      - ..:/opt/EpiGraphHub
    network_mode: host

  dev-epigraphhub-db:
    hostname: dev-epigraphhub-db
    build:
      context: ..
      dockerfile: docker/Dockerfile.db
    env_file:
      - ../.env
    environment:
      # overwrite .env default variables
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 25432:25432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 25432 -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    command: -p 25432
