
version: '3.4'

services:
  airflow-initdb:
    build: ./airflow/
    env_file:
      - ../.env
    entrypoint: "airflow db init"

  airflow:
    build: ./airflow/
    env_file:
      - ../.env
    restart: unless-stopped
    volumes:
      - ./airflow/files/dags:/usr/local/airflow/dags
    ports:
      - "8080:8080"
    entrypoint: "airflow webserver"
    depends_on:
      - airflow-scheduler
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 10

  airflow-scheduler:
    build: ./airflow/
    env_file:
      - ../.env
    restart: unless-stopped
    volumes:
      - ./airflow/files/dags:/usr/local/airflow/dags
    entrypoint: "airflow scheduler"
    healthcheck:
      test: ["CMD", "airflow", "jobs", "check", "--job-type", "SchedulerJob", "--hostname", "$$(hostname)"]
      interval: 30s
      timeout: 5s
      retries: 10
