name: epigraphhub
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python 3.9.*
  - awscli
  - git
  - make
  - sqlite
  - webdriver-manager
  - pip
  - pip:
    - containers-sugar==1.11.2
    - makim==1.15.0
    - compose-go
    - epigraphhub>=2.1.1
    - "selenium<=4.0"
