name: epigraphhub
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python 3.9.*
  - awscli
  - docker-compose
  - git
  - make
  - sqlite
  - python-chromedriver-binary
  - pip
  - pip:
    - epigraphhub
    - selenium
