name: epigraphhub
channels:
  - conda-forge
  - r
  - nodefaults
dependencies:
  - fiona
  - geopandas
  - gsheetsdb
  - inquirer
  - flask-mail
  - flask >=1.1.0,<2.0.0
  - lightgbm
  - loguru
  - myst-parser
  - openpyxl
  - pandas
  - pip
  - psycopg2
  - python 3.8.*
  - python-dotenv
  - setuptools
  - sqlalchemy
  - superset 2.0.0
  # waiting for https://github.com/stanfordmlgroup/ngboost/issues/283
  # - ngboost >=0.3.12
  # avoid error: ModuleNotFoundError: No module named 'wtforms.compat'
  # - wtforms <3
  # dev
  - virtualenv
  - ansible
  - sphinx
  - pip
  - docker-compose
  # TypeError: entry_points() got an unexpected keyword argument 'group'
  # - markdown 3.3.4
  # R
  - r-base 3.6.*
  - r-tidyverse
  - r-shiny
  - r-stringr
  - r-readxl
  - r-dplyr
  - r-dbi
  - r-vroom
  - r-odbc
  - r-rsocrata
  - r-glue
  - r-janitor
  - r-here
  - r-desctools
  - r-lubridate
  - r-isocodes
  # - r-dm
  - pip:
    - -r pip.txt
