---
- hosts: localhost
  connection: local
  vars_files:
    - ../vars/docker.yml

  tasks:
    - name: "Create .ssh folder"
      shell: mkdir -p ~/.ssh

    - name: Create an SSH Key Pair Secret
      copy:
        content: "{{ ssh_private_key }}"
        dest: "{{ ssh_private_file }}"
        mode: '600'
      tags: ssh-key

    # https://stackoverflow.com/a/32338480
    - name: Write the new ec2 instance host key to known hosts
      connection: local
      shell: "ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts"

    - name: "Check ssh connection"
      shell: ansible -i ../inventories/hosts.ini -m ping hetzner
      args:
        executable: /bin/bash
