---
- hosts: localhost
  connection: local
  vars_files:
    - ../vars/docker.yml

  environment:
    CONDA_PREFIX: "{{ HOST_CONDA_PREFIX }}"
    PATH: "{{ HOST_PATH }}"

  tasks:
    - name: "Create .ssh folder"
      shell: mkdir -p ~/.ssh

    - name: Create an SSH Key Pair Secret
      copy:
        content: "{{ ssh_private_key }}"
        dest: "{{ ssh_private_file }}"
        mode: '600'
      tags: ssh-key
