---
- hosts: localhost
  connection: local
  vars_files:
    - ../vars/docker.yml

  tasks:
    - name: "Create .ssh folder"
      shell: mkdir -p ~/.ssh

    - name: Create an SSH Key Pair Secret
      copy:
        content: "{{ ssh_private_key }}"
        dest: "{{ ssh_private_file }}"
        mode: '600'
      tags: ssh-key

    - name: "Check ssh connection"
      shell: ansible -i ansible/inventories/hosts.ini -m ping hetzner
      args:
        executable: /bin/bash
