AIRFLOW_PROJ_DIR=${AIRFLOW_PROJ_DIR}
AIRFLOW_UID=${AIRFLOW_UID}
AIRFLOW_PORT=${AIRFLOW_PORT}
_AIRFLOW_WWW_USER_USERNAME=${_AIRFLOW_WWW_USER_USERNAME}
_AIRFLOW_WWW_USER_PASSWORD=${_AIRFLOW_WWW_USER_PASSWORD}

AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
