---
- hosts: hetzner # or all or local
  become: yes
  vars_files:
    - vars/default.yml
  tasks:
    - name: Creates an entry like "PATH=/opt/bin" on top of crontab
      ansible.builtin.cron:
        name: JOBPATH
        env: yes
        job: /opt

    - name: Creates an entry like "HUB_HOME=/opt/EpiGraphHub/Data_Collection/CRON_scripts" and insert it after PATH declaration
      ansible.builtin.cron:
        name: HUB_HOME
        env: yes
        job: /opt/EpiGraphHub/Data_Collection/CRON_scripts

    - name: create owid download job
      ansible.builtin.cron:
        name: "Fetch owid data"
        minute: "0"
        hour: "1"
        job: "/opt/EpiGraphHub/Data_Collection/CRON_scripts/owid.sh"

    - name: create FOPH download job
      ansible.builtin.cron:
        name: "Fetch FOPH data"
        minute: "0"
        hour: "15"
        job: "/opt/EpiGraphHub/Data_Collection/CRON_scripts/foph.sh"

    - name: create make_forecast job
      ansible.builtin.cron:
        name: "Make forecasts"
        minute: "0"
        hour: "16"
        job: "/opt/EpiGraphHub/Data_Collection/CRON_scripts/forecast.sh"

    - name: create colombia job
      ansible.builtin.cron:
        name: "Download Colombia COVID cases"
        minute: "0"
        hour: "1"
        job: "/opt/EpiGraphHub/Data_Collection/CRON_scripts/colombia.sh"
